package com.zzstack.paas.underlying.metasvr.dataservice.dao.sql;

public class JvmStatisticSql {

    public static final String SQL_QUERY_JVM_INFO = "SELECT TS,INST_ID,JAVA_VERSION,GC_YOUNG_GC_COUNT," +
            "GC_YOUNG_GC_TIME,GC_FULL_GC_COUNT,GC_FULL_GC_TIME,THREAD_COUNT,THREAD_DAEMON_THREAD_COUNT," +
            "THREAD_PEEK_THREAD_COUNT,THREAD_DEADLOCKED_THREAD_COUNT,MEM_EDEN_INIT,MEM_EDEN_USED,MEM_EDEN_COMMITTED," +
            "MEM_EDEN_MAX,MEM_EDEN_USEDPERCENT,MEM_SURVIVOR_INIT,MEM_SURVIVOR_USED,MEM_SURVIVOR_COMMITTED," +
            "MEM_SURVIVOR_MAX,MEM_SURVIVOR_USEDPERCENT,MEM_OLD_INIT,MEM_OLD_USED,MEM_OLD_COMMITTED,MEM_OLD_MAX," +
            "MEM_OLD_USEDPERCENT,MEM_PERM_INIT,MEM_PERM_USED,MEM_PERM_COMMITTED,MEM_PERM_MAX,MEM_PERM_USEDPERCENT," +
            "MEM_CODE_INIT,MEM_CODE_USED,MEM_CODE_COMMITTED,MEM_CODE_MAX,MEM_CODE_USEDPERCENT,MEM_HEAP_INIT,MEM_HEAP_USED," +
            "MEM_HEAP_COMMITTED,MEM_HEAP_MAX,MEM_HEAP_USEDPERCENT,MEM_NOHEAP_INIT,MEM_NOHEAP_USED,MEM_NOHEAP_COMMITTED," +
            "MEM_NOHEAP_MAX,MEM_NOHEAP_USEDPERCENT FROM T_JVM_INFO ";
    
    public static final String SQL_ADD_JVM_INFO = "INSERT INTO ? (TS,INST_ID,JAVA_VERSION,GC_YOUNG_GC_COUNT,"  +
            "GC_YOUNG_GC_TIME,GC_FULL_GC_COUNT,GC_FULL_GC_TIME,THREAD_DAEMON_THREAD_COUNT,THREAD_COUNT,"  +
            "THREAD_PEEK_THREAD_COUNT,THREAD_DEADLOCKED_THREAD_COUNT,MEM_EDEN_INIT,MEM_EDEN_USED,MEM_EDEN_COMMITTED,"  +
            "MEM_EDEN_MAX,MEM_EDEN_USEDPERCENT,MEM_SURVIVOR_INIT,MEM_SURVIVOR_USED,MEM_SURVIVOR_COMMITTED," +
            "MEM_SURVIVOR_MAX,MEM_SURVIVOR_USEDPERCENT,MEM_OLD_INIT,MEM_OLD_USED,MEM_OLD_COMMITTED,MEM_OLD_MAX," +
            "MEM_OLD_USEDPERCENT,MEM_PERM_INIT,MEM_PERM_USED,MEM_PERM_COMMITTED,MEM_PERM_MAX,MEM_PERM_USEDPERCENT," +
            "MEM_CODE_INIT,MEM_CODE_USED,MEM_CODE_COMMITTED,MEM_CODE_MAX,MEM_CODE_USEDPERCENT,MEM_HEAP_INIT,MEM_HEAP_USED," +
            "MEM_HEAP_COMMITTED,MEM_HEAP_MAX,MEM_HEAP_USEDPERCENT,MEM_NOHEAP_INIT,MEM_NOHEAP_USED,MEM_NOHEAP_COMMITTED,"  +
            "MEM_NOHEAP_MAX,MEM_NOHEAP_USEDPERCENT) USING T_JVM_INFO (INSTANT_ID) TAGS (?) " +
            "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

}
