package com.zzstack.paas.underlying.metasvr.dataservice.dao.sql;

public class RedisStatisticSql {

    public static final String SQL_QUERY_REDIS_INSTANCE_INFO = "SELECT TS,ROLE,INST_ID,CONNECTED_CLIENTS,USED_MEMORY,"
            + "MAXMEMORY,INSTANTANEOUS_OPS_PER_SEC,INSTANTANEOUS_INPUT_KBPS,INSTANTANEOUS_OUTPUT_KBPS,SYNC_FULL,"
            + "EXPIRED_KEYS,EVICTED_KEYS,KEYSPACE_HITS,KEYSPACE_MISSES,USED_CPU_SYS,USED_CPU_USER FROM T_REDIS_INFO ";
    
    public static final String SQL_ADD_REDIS_INFO = "INSERT INTO ? (TS,INST_ID,ROLE,CONNECTED_CLIENTS,"
            + "USED_MEMORY,MAXMEMORY,INSTANTANEOUS_OPS_PER_SEC,INSTANTANEOUS_INPUT_KBPS,INSTANTANEOUS_OUTPUT_KBPS,"
            + "SYNC_FULL,EXPIRED_KEYS,EVICTED_KEYS,KEYSPACE_HITS,KEYSPACE_MISSES,USED_CPU_SYS,USED_CPU_USER) "
            + "USING T_REDIS_INFO (INSTANT_ID) TAGS (?) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

}
