/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smsbase_firmware_FirmwareNative */

#ifndef _Included_com_smsbase_firmware_FirmwareNative
#define _Included_com_smsbase_firmware_FirmwareNative

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring Java_com_zzstack_paas_underlying_firmware_FirmwareNative_cpuid
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_zzstack_paas_underlying_firmware_FirmwareNative_encrypt
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_com_zzstack_paas_underlying_firmware_FirmwareNative_checkFirmware
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif

#endif
