package consts

const (
	CMD_SETH_PLUS = "set +H"
	CMD_TAIL      = "tail"
	CMD_CD        = "cd"
	CMD_PWD       = "pwd"
	CMD_CP        = "cp"
	CMD_SCP       = "scp"
	CMD_FILE      = "file"
	CMD_MKDIR     = "mkdir"
	CMD_TAR       = "tar"
	CMD_UNZIP     = "unzip"
	CMD_EXPORT    = "export"
	CMD_CAT       = "cat"
	CMD_TOUCH     = "touch"
	CMD_CAT_END   = "EOF"
	CMD_SOURCE    = "source"
	CMD_NETSTAT   = "netstat"
	CMD_ECHO      = "echo"
	CMD_MV        = "mv"
	CMD_RM        = "rm"
	CMD_CHMOD     = "chmod"
	CMD_HOSTNAME  = "hostname"
	CMD_HNAME2IP  = "hname2ip"
	CMD_ERL       = "erl"
	CMD_SED       = "sed"
	CMD_DIR       = "dir"
	CMD_SET_PS1   = "export PS1=\"[\\u@\\h \\W]\\$ \""
	CMD_DOS2UNIX  = "dos2unix"
	CMD_PS        = "ps"
	SHELL_MACRO   = "#! /bin/sh"
	CMD_PING      = "PING\r\n"
)
