package consts

var (
	ERR_LDBPOOL_YAML_INIT            = "LdbDbPool Init error, dbYaml nil ......"
	ERR_REDIS_POOL_NIL               = "redis pool get connection result nil"
	ERR_PARAM_INCOMPLETE             = "parameter incomplete ......"
	ERR_TIDB_CONTAINER_META          = "tidb container component meta error ......"
	ERR_JSON_SCHEME_VALI_ERR         = "json schema validation fail ......"
	ERR_SCHEMA_FILE_NOT_EXIST        = "schema file not exist ......"
	ERR_METADATA_NOT_FOUND           = "meta data not found ......"
	ERR_JSONNODE_NOT_COMPLETE        = "json node not complete ......"
	ERR_SERV_TYPE_NOT_FOUND          = "service type not found ......"
	ERR_HOSTINFO_NOT_COMPLETE        = "host info not complete ......"
	ERR_DEPLOY_CONF_MISS             = "deploy file config missing ......"
	ERR_SSH_CONNECT_FAIL             = "ssh connect fail ......"
	ERR_EXEC_SHELL_FAIL              = "exec shell fail ......"
	ERR_DEPLOY_ERL_FAIL              = "deploy erlang fail ......"
	ERR_SET_HOSTS_FAIL               = "set hosts fail ......"
	ERR_MQ_PORT_ISUSED               = "MQ port is used ......"
	ERR_MQ_NO_BROKER_FUND            = "no broker found ......"
	ERR_DEPLOY_MQ_FAIL               = "deploy mq fail ......"
	ERR_UNDEPLOY_MQ_FAIL             = "undeploy mq fail ......"
	ERR_SET_HOST                     = "set hosts fail ......"
	ERR_SET_ERLCOOKIE                = "set erlang cookie fail ......"
	ERR_RABBITMQ_PORT_USED           = "rabbitmq port is used ......"
	ERR_RABBITMQ_MGR_PORT_USED       = "rabbitmq manage port is used ......"
	ERR_PORT_USED_IN_DB              = "port is used in db ......"
	ERR_PWD_INCORRECT                = "login passwd incorrect ......"
	ERR_PWD_EXPIRE                   = "login passwd expired ......"
	ERR_PUT_SESSION                  = "put session fail ......"
	ERR_ACCOUNT_NOT_EXISTS           = "account not exists ......"
	ERR_PAAS_SERVICE_INIT_FAIL       = "paas service init fail ......"
	ERR_LOGIN_TIMOUT_OR_NOT_LOGINED  = "登陆认证过期或未登陆，请重新登陆再改密!"
	ERR_CLEAR_ALARM_REDIS_CACHE_FAIL = "clear alarm redis cache fail ......"
	ERR_DB                           = "db error"
	ERR_NO_DEL_DEPLOYED_SERV         = "cannot delete deployed service ......"
	ERR_SERVER_IP_EXISTS             = "server ip exists ......"
	ERR_SERVER_NOT_NULL              = "server contains sub ssh, can not delete ......"
	ERR_SSH_IS_USING                 = "ssh resource is using, can not delete ......"
	ERR_JSONNODE_ILLEGAL             = "json node illegal"
	ERR_OP_TYPE                      = "OP_TYPE error"
	ERR_CMPT_NOT_FOUND               = "component not found ......"
	ERR_INSTANCE_NOT_FOUND           = "instance not found ......"
	ERR_REDIS_QUEUE_NOT_INITIALIZED  = "redis A/B cluster queue service not initialized ......"
)
